#!/usr/bin/env python3
"""
Build derived success / failed / top-100 corpora from all-corpus.json.

This replaces the old refresh-corpus.py thresholds. Selection criteria are
now grounded in the true Show HN point distribution (n=196k):
- ≤1pt = 28.3%, ≤5pt = 74.3%, ≥262pt = 1.0%, ≥676pt = 0.1%
- Success = top 1% by points (≥262pt) — about 2000 entries
- Failed = random sample of 5000 ≤5pt posts (representative of base rate)
- Top 100 = top 100 by points for examples reference

Also regenerates posting-time.md from the full corpus (no longer
limited to the prior 999 high-relevance subset).
"""
from __future__ import annotations

import argparse
import json
import random
import statistics
import sys
import urllib.parse
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

SKILL_ROOT = Path(__file__).resolve().parent.parent
ALL_PATH = SKILL_ROOT / "patterns" / "all-corpus.json"
SUCCESS_PATH = SKILL_ROOT / "patterns" / "corpus.json"
TOP100_PATH = SKILL_ROOT / "patterns" / "top-100.json"
FAILED_PATH = SKILL_ROOT / "patterns" / "failed-corpus.json"
POSTING_TIME_PATH = SKILL_ROOT / "patterns" / "posting-time.md"

SUCCESS_POINT_THRESHOLD = 262   # ~top 1%
FAILED_POINT_CEILING = 5        # bottom mass
FAILED_SAMPLE_SIZE = 5000
RNG_SEED = 20260618


def dedup_key(url: str | None) -> str | None:
    if not url:
        return None
    try:
        parsed = urllib.parse.urlparse(url)
    except ValueError:
        return None
    host = parsed.netloc.lower().replace("www.", "")
    if host != "github.com":
        return None
    parts = [p for p in parsed.path.split("/") if p]
    if len(parts) < 2:
        return None
    return f"github.com/{parts[0]}/{parts[1]}"


def dedup(hits: list[dict]) -> tuple[list[dict], int]:
    by_key: dict[str, dict] = {}
    pass_through: list[dict] = []
    for h in hits:
        k = dedup_key(h.get("url"))
        if k is None:
            pass_through.append(h)
            continue
        prev = by_key.get(k)
        if prev is None or (h.get("points") or 0) > (prev.get("points") or 0):
            by_key[k] = h
    return pass_through + list(by_key.values()), len(hits) - len(by_key) - len(pass_through) + len(by_key) - (len(pass_through) + len(by_key))


def select_success(all_hits: list[dict]) -> list[dict]:
    high = [h for h in all_hits if (h.get("points") or 0) >= SUCCESS_POINT_THRESHOLD]
    deduped, _ = dedup(high)
    deduped.sort(key=lambda h: -(h.get("points") or 0))
    return deduped


def select_failed(all_hits: list[dict]) -> list[dict]:
    low = [h for h in all_hits if (h.get("points") or 0) <= FAILED_POINT_CEILING]
    rng = random.Random(RNG_SEED)
    sample = rng.sample(low, min(FAILED_SAMPLE_SIZE, len(low)))
    sample.sort(key=lambda h: -(h.get("created_at_i") or 0))
    return sample


def render_posting_time(success_hits: list[dict]) -> str:
    """Re-render posting-time.md using the new success cohort."""
    dow_pts = defaultdict(list)
    hour_pts = defaultdict(list)
    dow_hour_pts = defaultdict(list)
    dow_names = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]

    for h in success_hits:
        if not h.get("created_at") or not h.get("points"):
            continue
        try:
            dt = datetime.fromisoformat(h["created_at"].replace("Z", "+00:00"))
        except ValueError:
            continue
        et_hour = (dt.astimezone(timezone.utc).hour - 5) % 24
        dow = dt.astimezone(timezone.utc).weekday()
        pts = h["points"]
        dow_pts[dow].append(pts)
        hour_pts[et_hour].append(pts)
        dow_hour_pts[(dow, et_hour)].append(pts)

    def percentile(sv, p):
        return sv[min(len(sv) - 1, int(len(sv) * p))] if sv else 0

    dow_lines = []
    for d in range(7):
        pts = sorted(dow_pts[d])
        if not pts:
            continue
        dow_lines.append(
            f"| {dow_names[d]} | {len(pts)} | {statistics.median(pts):.0f} | "
            f"{percentile(pts, 0.75)} | {percentile(pts, 0.90)} |"
        )

    hour_lines = []
    for h in range(0, 24):
        pts = sorted(hour_pts[h])
        if not pts:
            continue
        hour_lines.append(
            f"| {h} | {len(pts)} | {statistics.median(pts):.0f} | {percentile(pts, 0.75)} |"
        )

    qualified = [
        ((d, h), statistics.median(v))
        for (d, h), v in dow_hour_pts.items()
        if len(v) >= 20
    ]
    qualified.sort(key=lambda kv: -kv[1])
    bucket_lines = [
        f"| {dow_names[d]} {h:>2} ET | {m:.0f} | {len(dow_hour_pts[(d, h)])} |"
        for (d, h), m in qualified[:10]
    ]

    today = datetime.now(timezone.utc).date().isoformat()
    n = len(success_hits)
    return f"""# Posting time analysis

Auto-generated by `tools/build-corpora.py` on {today}. Source: `corpus.json` ({n} Show HN posts at or above {SUCCESS_POINT_THRESHOLD} points — true top 1% of the Show HN distribution). Times converted from UTC to ET using a fixed UTC-5 offset (DST drift ±1h tolerated).

## Caveat — survivor bias

The corpus contains only high-scoring posts. This data answers "when do top performers tend to post", not "when does posting maximize the chance of becoming a top performer". Treat the windows below as where the survivors cluster, not as a guarantee. With n={n}, samples are large enough that the windows are stable across refreshes.

## Day of week (ET)

| Day | n | median pts | p75 | p90 |
|---|---|---|---|---|
{chr(10).join(dow_lines)}

## Hour of day (ET) — full 24h

| Hour ET | n | median | p75 |
|---|---|---|---|
{chr(10).join(hour_lines)}

## Top 10 (dow, hour) buckets — n ≥ 20

| Slot | median pts | n |
|---|---|---|
{chr(10).join(bucket_lines)}

## Recommendation

See the top-10 table for the data-derived posting windows. KST conversion: subtract 14h from ET (so ET 9:00 = KST 22:00 prior day).

<!-- Auto-rewritten on every refresh; do not hand-edit above this line. -->

## What this data does NOT cover

- Time-of-year effects (holiday weeks etc.)
- Topic-specific timing
- Counterfactuals: whether the same post would do better at a different time
- Front-page duration after the post hour
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass

    all_hits = json.loads(ALL_PATH.read_text(encoding="utf-8"))
    print(f"[build-corpora] loaded {len(all_hits)} total Show HN entries")

    success = select_success(all_hits)
    failed = select_failed(all_hits)
    top100 = success[:100]
    print(f"[build-corpora] success (≥{SUCCESS_POINT_THRESHOLD}pt, deduped): {len(success)}")
    print(f"[build-corpora] failed   (≤{FAILED_POINT_CEILING}pt, sampled): {len(failed)}")
    print(f"[build-corpora] top 100 cutoff at {top100[-1].get('points')}pt")

    if args.dry_run:
        print("[dry-run] no files written")
        return 0

    SUCCESS_PATH.write_text(json.dumps(success, ensure_ascii=False, indent=0), encoding="utf-8")
    FAILED_PATH.write_text(json.dumps(failed, ensure_ascii=False, indent=0), encoding="utf-8")
    TOP100_PATH.write_text(json.dumps(top100, ensure_ascii=False, indent=2), encoding="utf-8")
    POSTING_TIME_PATH.write_text(render_posting_time(success), encoding="utf-8")
    print(f"[build-corpora] wrote corpus.json, failed-corpus.json, top-100.json, posting-time.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
